from .libs.init import init
init()
from galite import P, S, A, N, input_text, set_theme # noqa: E402

P('Argon','你好，欢迎来到RE:now!text')
P('Argon','这是默认的教程关卡，用于让你快速熟悉RE:now!text')
P('Argon','这是一个对话内容，它使用"P"函数，就是print的意思，你可能发现我们的print有点不一样，因为他是Rich的print')
S('Argon','这是"S"函数，用于接收用户输入，输入的内容会被保存到"input_text[0]"中\n你可以输入任何内容！')
P('Argon',f'你输入的内容是：{input_text[0]}，对吧？')
P('Argon','你可以通过"theme"函数来更改主题')
set_theme('double')
P('Argon','现在的主题是 double 了！')
set_theme('single')
P('Argon','现在的主题是 single 了！')
set_theme('ascii')
P('Argon','现在的主题是 ascii 了！')
set_theme('rounded')
P('Argon','现在的主题变回 rounded 了！')
P('Argon','接下来，隆重介绍——取得进度"A"')
A('这是一个进度', 0)
A('这是一个目标', 1)
A('这是一个挑战', 2)
P('Argon','你可以使用"N"来跳转到其它关卡，\n使用"E"退出（虽然但是好像执行完就退出了吧🤔）\n使用"E"退出会在退出前执行清屏，并且可以带状态码\n此外，你可以直接运行关卡文件，上面的 init() 已经初始化好了，无需担心目录问题')
P('Argon','好了，这就是RE:now!text的基本操作了！祝你游戏愉快！接下来会使用"N"来进入下一个教程！')
N('level2')